;================================ TRANSPORTS ==
; Our primary transport definition for UDP communication behind NAT.
[transport-udp-nat]
type = transport
protocol = udp
bind = 0.0.0.0
; NAT settings
;local_net = 10.0.0.0/8
;external_media_address = 203.0.113.1
;external_signaling_address = 203.0.113.1

[auth-userpass](!)
type = auth
auth_type = userpass

;================================ ENDPOINT DEFINITIONS ==
; Below are the definitions for all staff devices, listed by department.
;
; Super Awesome Company uses the MAC address of their devices for the auth
; username and the extension number for the name of the endpoint, auth and
; aor objects. If your phones must use the same user ID and auth name then
; you will need to customize the endpoints accordingly.

;================================ MANAGEMENT ==

[1107](auth-userpass)
password = 4webrEtHupHewu4
username = 0019159BF771

[1109](auth-userpass)
password = sPeFaChe7ruxarE
username = 00094558B29E

[1101](auth-userpass)
password = SW2fur7facrarac
username = 3605657CFB45

[1106](auth-userpass)
password = tecrUBUs3u7uTab
username = EAFB2F4319C4

;================================ PERSONAL TESTS MANAGEMENT ==

[1000]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=1000-auth
aors=1000
direct_media = no

[1000-auth](auth-userpass)
username=1000
password=test

[1000]
type=aor
max_contacts=5

[kamailio-edge]
type=endpoint
context=from-kamailio
disallow=all
allow=ulaw,alaw,g722
aors=kamailio-edge
trust_id_inbound=yes
send_pai=yes

[kamailio-edge]
type=aor
contact=sip:127.25.0.3:5060

[kamailio-edge-identify]
type=identify
endpoint=kamailio-edge
match=127.25.0.3
